### ISSUE TITLE
what's the difference between bpt.so and gentrace.so

### ISSUE THREAD

**Issue by yuruifei** [BinaryAnalysisPlatform/bap-pintraces#8]
The earlier version of pintraces generates gentrace.so only. Now  bpt.so was added. The README.md says gentrace.so records taint information  while bpt.so just record trace data.

My question is 
1. gentrace.so records the tainted instructions and neglect other instructions, whereas bpt.so records all the instructions executed. Is that right?
2. If so, is there any other difference?
3. i do  not quite understand the taint propogating policy in pin_taint.cpp. Any document?
4. Is there any relationship between bap taint plugin and pin_taint

**Comment by ivg** [comment]
> gentrace.so records the tainted instructions and neglect other instructions, whereas bpt.so records all the instructions executed. Is that right?

yes.

> If so, is there any other difference?

The `bpt` tracer tracks read and write operations more precisely. It also tracks reads and writes to the status register. The main purpose of this tracer is to provide a precise trace of program execution. 

> i do not quite understand the taint propogating policy in pin_taint.cpp. Any document?

Me neither. And no, there is no documentation, as far as I know. 

> Is there any relationship between bap taint plugin and pin_taint

Besides that they both do tainting no. The BAP taint plugin performs taint analysis using microexecution (interpreting of the lifted code), where the PIN tainter performs tainting using real execution.
